title: Deeraj Nagothu
description: An internet homestead to explore entropy
author: Deeraj Nagothu
avatar: /logo.png
email: deerajnagothu@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
disqus: exploringentropy

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: deerajnagothu
  card: summary
logo: logo.png
social:
  name: Deeraj Nagothu
  links:
    - https://twitter.com/deerajnagothu
    - https://github.com/deerajnagothu
google_site_verification: 6Et_wZUc2OZg1dSq2-cxJT6RODHk81cizJYCBeq_1rc
lang: en
